// 扩展的Mock数据 - 包含Agent推理链路、RAG召回、SOP匹配等完整数据

export type AgentChainStep = {
  id: "perceive" | "mine" | "strategy";
  name: string;
  timestamp: string;
  confidence: number;
  input: string;
  action: string;
  output: string;
  dataSource?: string;
};

export type SimilarCase = {
  id: string;
  title: string;
  similarity: number;
  lifecycle: string;
  strategy: string;
  effect: {
    playback: string;
    engagement: string;
  };
  date: string;
};

export type SOPMatch = {
  id: string;
  name: string;
  confidence: number;
  reason: string;
  content: string;
};

export type PredictedEffect = {
  playback: { value: string; baseline: string };
  engagement: { value: string; baseline: string };
  conversion: { value: string; baseline: string };
};

export type RiskWarning = {
  level: "low" | "medium" | "high";
  message: string;
  detail: string;
};

export type ExtendedEventData = {
  agentChain: AgentChainStep[];
  similarCases: SimilarCase[];
  sopMatch: SOPMatch;
  predictedEffect: PredictedEffect;
  riskWarnings: RiskWarning[];
  heatTrend: Array<{ time: string; value: number; predicted?: boolean }>;
};

// 10条完整的Mock事件数据
export const mockEvents = [
  {
    id: "EVT_20260517_001",
    title: "SANA-WM：一个用于生成1分钟720p视频的26亿级开源世界模型",
    summary: "NVIDIA研究团队发布了SANA-WM，这是一个26亿参数的开源世界模型，能够生成1分钟的720p高质量视频。该模型在视频生成质量和效率上都有显著提升。",
    source: "Hacker News",
    heatScore: 97,
    heatLevel: "S" as const,
    lifecycle: "emerging" as const,
    lifecycleLabel: "萌芽期",
    riskLevel: "low" as const,
    eventType: "ai-model" as const,
    eventTypeLabel: "模型发布",
    publishedAt: "2026-05-17T08:25:00Z",
    ageHours: 2,
    scoreFactors: [
      { label: "时效信号", value: 26, max: 28, evidence: "最近24小时内发布，处于可运营窗口" },
      { label: "传播速度", value: 18, max: 25, evidence: "增速高于同类事件中位数" },
      { label: "作者密度", value: 12, max: 15, evidence: "NVIDIA官方发布，权威性高" },
      { label: "情感倾向", value: 15, max: 15, evidence: "正向情感占比92%，用户期待度高" },
      { label: "内容质量", value: 18, max: 15, evidence: "技术细节完整，有demo展示" },
      { label: "平台适配度", value: 8, max: 17, evidence: "技术类内容，需要降低理解门槛" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "23:25",
        confidence: 92,
        input: "Hacker News热门条目",
        action: "发现线索：提取标题、来源、摘要、发布时间",
        output: "识别为模型发布类事件，来源可信度高",
        dataSource: "Hacker News API",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "23:26",
        confidence: 88,
        input: "结构化事件数据 + 历史事件图谱",
        action: "事件聚类：计算热度因子、判定生命周期、评估影响",
        output: "热度97分(S级)，萌芽期，建议2小时内介入",
        dataSource: "事件知识图谱 + 向量数据库",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "23:27",
        confidence: 85,
        input: "事件画像 + SOP库 + 历史案例",
        action: "SOP匹配：检索相似案例，生成运营策略",
        output: "匹配SOP-TECH-001，推荐技术解读+二创激励策略",
        dataSource: "SOP知识库 + RAG召回",
      },
    ],
    similarCases: [
      {
        id: "CASE_001",
        title: "Stability AI发布Stable Diffusion 3",
        similarity: 87,
        lifecycle: "萌芽期 → 爆发期",
        strategy: "技术解读 + 二创激励",
        effect: {
          playback: "+156%",
          engagement: "+22%",
        },
        date: "2026-03-15",
      },
      {
        id: "CASE_002",
        title: "Runway Gen-3发布",
        similarity: 72,
        lifecycle: "萌芽期 → 爆发期",
        strategy: "产品对比 + 使用教程",
        effect: {
          playback: "+134%",
          engagement: "+18%",
        },
        date: "2026-04-08",
      },
      {
        id: "CASE_003",
        title: "Pika 1.5更新",
        similarity: 65,
        lifecycle: "爆发期 → 成熟期",
        strategy: "功能测评 + 场景应用",
        effect: {
          playback: "+98%",
          engagement: "+12%",
        },
        date: "2026-02-20",
      },
    ],
    sopMatch: {
      id: "SOP-TECH-001",
      name: "技术类模型发布-萌芽期-低风险",
      confidence: 85,
      reason: "事件类型匹配、生命周期匹配、风险等级匹配",
      content: "针对技术类模型发布事件，在萌芽期采用技术解读+二创激励的组合策略，预期播放量提升130%，互动率提升15%",
    },
    predictedEffect: {
      playback: { value: "+130%", baseline: "vs不运营" },
      engagement: { value: "+15%", baseline: "vs同类平均" },
      conversion: { value: "+2.1%", baseline: "粉丝转化率" },
    },
    riskWarnings: [
      {
        level: "low" as const,
        message: "该策略在娱乐类事件中效果下降40%",
        detail: "请确认事件分类准确，避免策略误用",
      },
    ],
    heatTrend: [
      { time: "08:00", value: 85 },
      { time: "09:00", value: 92 },
      { time: "10:00", value: 97 },
      { time: "11:00", value: 103, predicted: true },
      { time: "12:00", value: 108, predicted: true },
      { time: "13:00", value: 105, predicted: true },
    ],
  },
  {
    id: "EVT_20260517_002",
    title: "某顶流明星演唱会门票秒罄，二级市场溢价超300%",
    summary: "知名歌手演唱会门票开售即秒罄，二级市场价格暴涨，引发热议",
    source: "微博热搜",
    heatScore: 89,
    heatLevel: "A" as const,
    lifecycle: "burst" as const,
    lifecycleLabel: "爆发期",
    riskLevel: "medium" as const,
    eventType: "industry" as const,
    eventTypeLabel: "娱乐",
    publishedAt: "2026-05-17T02:15:00Z",
    ageHours: 8,
    scoreFactors: [
      { label: "时效信号", value: 21, max: 28, evidence: "24小时内，仍在热度窗口" },
      { label: "传播速度", value: 22, max: 25, evidence: "微博热搜Top3" },
      { label: "作者密度", value: 14, max: 15, evidence: "多个大V参与讨论" },
      { label: "情感倾向", value: 10, max: 15, evidence: "情感两极分化" },
      { label: "内容质量", value: 12, max: 15, evidence: "有现场图片和数据" },
      { label: "平台适配度", value: 10, max: 17, evidence: "娱乐类内容，需注意价值观" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "02:20",
        confidence: 88,
        input: "微博热搜榜单",
        action: "发现线索：娱乐类热点，情感两极",
        output: "识别为娱乐事件，需注意舆论导向",
        dataSource: "微博API",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "02:21",
        confidence: 85,
        input: "事件数据 + 舆情分析",
        action: "事件聚类：分析情感倾向、评估风险",
        output: "热度89分(A级)，爆发期，中等风险",
        dataSource: "舆情分析系统",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "02:22",
        confidence: 82,
        input: "事件画像 + 风险评估",
        action: "SOP匹配：生成娱乐类运营策略",
        output: "匹配SOP-ENT-002，建议理性讨论角度",
        dataSource: "SOP知识库",
      },
    ],
    similarCases: [
      {
        id: "CASE_004",
        title: "某演唱会门票抢购热",
        similarity: 78,
        lifecycle: "爆发期 → 成熟期",
        strategy: "理性讨论 + 用户观点",
        effect: {
          playback: "+85%",
          engagement: "+10%",
        },
        date: "2026-01-10",
      },
    ],
    sopMatch: {
      id: "SOP-ENT-002",
      name: "娱乐类事件-爆发期-中风险",
      confidence: 82,
      reason: "娱乐类事件，需注意价值观导向",
      content: "采用理性讨论角度，避免煽动情绪，引导正向讨论",
    },
    predictedEffect: {
      playback: { value: "+85%", baseline: "vs不运营" },
      engagement: { value: "+10%", baseline: "vs同类平均" },
      conversion: { value: "+1.5%", baseline: "粉丝转化率" },
    },
    riskWarnings: [
      {
        level: "medium" as const,
        message: "情感两极分化，需注意舆论导向",
        detail: "避免煽动情绪，引导理性讨论",
      },
    ],
    heatTrend: [
      { time: "02:00", value: 65 },
      { time: "04:00", value: 78 },
      { time: "06:00", value: 85 },
      { time: "08:00", value: 89 },
      { time: "10:00", value: 92, predicted: true },
      { time: "12:00", value: 88, predicted: true },
    ],
  },
  {
    id: "EVT_20260517_003",
    title: "OpenAI发布GPT-5技术报告，多模态推理能力大幅提升",
    summary: "OpenAI正式发布GPT-5技术报告，展示了在多模态推理、长文本理解等方面的突破性进展",
    source: "抖音站内",
    heatScore: 95,
    heatLevel: "S" as const,
    lifecycle: "emerging" as const,
    lifecycleLabel: "萌芽期",
    riskLevel: "low" as const,
    eventType: "ai-model" as const,
    eventTypeLabel: "模型发布",
    publishedAt: "2026-05-17T06:30:00Z",
    ageHours: 4,
    scoreFactors: [
      { label: "时效信号", value: 26, max: 28, evidence: "4小时内发布，极佳时效" },
      { label: "传播速度", value: 24, max: 25, evidence: "OpenAI官方发布，传播迅速" },
      { label: "作者密度", value: 13, max: 15, evidence: "多个技术博主转发" },
      { label: "情感倾向", value: 15, max: 15, evidence: "高度正向，期待值高" },
      { label: "内容质量", value: 17, max: 15, evidence: "官方技术报告，内容详实" },
      { label: "平台适配度", value: 0, max: 17, evidence: "需要技术解读" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "06:35",
        confidence: 95,
        input: "抖音站内热点",
        action: "发现线索：OpenAI重大发布",
        output: "识别为S级模型发布事件",
        dataSource: "抖音热点API",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "06:36",
        confidence: 92,
        input: "事件数据 + 技术分析",
        action: "事件聚类：评估技术影响力",
        output: "热度95分(S级)，萌芽期，建议立即介入",
        dataSource: "技术知识图谱",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "06:37",
        confidence: 90,
        input: "事件画像 + 历史GPT发布案例",
        action: "SOP匹配：生成技术解读策略",
        output: "匹配SOP-TECH-002，推荐深度解读+应用场景",
        dataSource: "SOP知识库 + 历史案例",
      },
    ],
    similarCases: [
      {
        id: "CASE_005",
        title: "GPT-4发布",
        similarity: 92,
        lifecycle: "萌芽期 → 爆发期",
        strategy: "技术解读 + 应用场景",
        effect: {
          playback: "+280%",
          engagement: "+35%",
        },
        date: "2023-03-14",
      },
      {
        id: "CASE_006",
        title: "Claude 3发布",
        similarity: 85,
        lifecycle: "萌芽期 → 爆发期",
        strategy: "对比测评 + 使用指南",
        effect: {
          playback: "+210%",
          engagement: "+28%",
        },
        date: "2024-03-04",
      },
    ],
    sopMatch: {
      id: "SOP-TECH-002",
      name: "重大模型发布-萌芽期-低风险",
      confidence: 90,
      reason: "OpenAI重大发布，历史数据充足",
      content: "采用深度技术解读+实际应用场景的策略，预期效果显著",
    },
    predictedEffect: {
      playback: { value: "+250%", baseline: "vs不运营" },
      engagement: { value: "+30%", baseline: "vs同类平均" },
      conversion: { value: "+5.2%", baseline: "粉丝转化率" },
    },
    riskWarnings: [],
    heatTrend: [
      { time: "06:00", value: 88 },
      { time: "07:00", value: 92 },
      { time: "08:00", value: 95 },
      { time: "09:00", value: 102, predicted: true },
      { time: "10:00", value: 110, predicted: true },
      { time: "11:00", value: 115, predicted: true },
    ],
  },
  {
    id: "EVT_20260517_004",
    title: "某地出台AI监管新规，要求大模型训练数据需标注来源",
    summary: "地方政府发布AI监管新规，对大模型训练数据来源提出明确要求",
    source: "新闻网站",
    heatScore: 72,
    heatLevel: "B" as const,
    lifecycle: "mature" as const,
    lifecycleLabel: "成熟期",
    riskLevel: "high" as const,
    eventType: "industry" as const,
    eventTypeLabel: "政策法规",
    publishedAt: "2026-05-15T10:00:00Z",
    ageHours: 48,
    scoreFactors: [
      { label: "时效信号", value: 15, max: 28, evidence: "48小时前发布，进入成熟期" },
      { label: "传播速度", value: 16, max: 25, evidence: "传播速度中等" },
      { label: "作者密度", value: 10, max: 15, evidence: "部分媒体报道" },
      { label: "情感倾向", value: 8, max: 15, evidence: "情感中性偏谨慎" },
      { label: "内容质量", value: 13, max: 15, evidence: "有政策原文" },
      { label: "平台适配度", value: 10, max: 17, evidence: "政策类内容，需谨慎处理" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "10:05",
        confidence: 75,
        input: "新闻网站条目",
        action: "发现线索：政策法规类事件",
        output: "识别为高风险政策事件",
        dataSource: "新闻聚合API",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "10:06",
        confidence: 72,
        input: "事件数据 + 政策分析",
        action: "事件聚类：评估政策影响",
        output: "热度72分(B级)，成熟期，高风险",
        dataSource: "政策知识库",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "10:07",
        confidence: 68,
        input: "事件画像 + 风险评估",
        action: "SOP匹配：生成政策解读策略",
        output: "匹配SOP-GOV-001，需人工复核",
        dataSource: "SOP知识库",
      },
    ],
    similarCases: [
      {
        id: "CASE_007",
        title: "AI监管政策发布",
        similarity: 70,
        lifecycle: "成熟期",
        strategy: "政策解读 + 影响分析",
        effect: {
          playback: "+45%",
          engagement: "+8%",
        },
        date: "2025-11-20",
      },
    ],
    sopMatch: {
      id: "SOP-GOV-001",
      name: "政策法规类-成熟期-高风险",
      confidence: 68,
      reason: "政策类事件，需严格审核",
      content: "采用客观解读角度，避免主观评论，需人工复核",
    },
    predictedEffect: {
      playback: { value: "+45%", baseline: "vs不运营" },
      engagement: { value: "+8%", baseline: "vs同类平均" },
      conversion: { value: "+0.8%", baseline: "粉丝转化率" },
    },
    riskWarnings: [
      {
        level: "high" as const,
        message: "政策类内容，需严格审核",
        detail: "避免主观评论，确保事实准确，需人工复核后发布",
      },
    ],
    heatTrend: [
      { time: "10:00", value: 68 },
      { time: "14:00", value: 72 },
      { time: "18:00", value: 70 },
      { time: "22:00", value: 68, predicted: true },
      { time: "02:00", value: 65, predicted: true },
    ],
  },
  {
    id: "EVT_20260517_005",
    title: "NBA总决赛G3：湖人逆转勇士，詹姆斯三双创纪录",
    summary: "NBA总决赛第三场，湖人队在落后20分的情况下完成逆转，詹姆斯贡献三双数据并创造历史纪录",
    source: "抖音站内",
    heatScore: 85,
    heatLevel: "A" as const,
    lifecycle: "burst" as const,
    lifecycleLabel: "爆发期",
    riskLevel: "low" as const,
    eventType: "industry" as const,
    eventTypeLabel: "体育",
    publishedAt: "2026-05-17T04:00:00Z",
    ageHours: 6,
    scoreFactors: [
      { label: "时效信号", value: 24, max: 28, evidence: "6小时内，热度窗口" },
      { label: "传播速度", value: 20, max: 25, evidence: "体育类热点，传播快" },
      { label: "作者密度", value: 12, max: 15, evidence: "多个体育博主报道" },
      { label: "情感倾向", value: 14, max: 15, evidence: "高度正向，球迷热情" },
      { label: "内容质量", value: 15, max: 15, evidence: "有比赛视频和数据" },
      { label: "平台适配度", value: 0, max: 17, evidence: "体育内容，受众广" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "04:10",
        confidence: 90,
        input: "抖音体育热点",
        action: "发现线索：NBA总决赛重大事件",
        output: "识别为A级体育事件",
        dataSource: "抖音体育频道",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "04:11",
        confidence: 88,
        input: "事件数据 + 体育分析",
        action: "事件聚类：评估赛事影响",
        output: "热度85分(A级)，爆发期，低风险",
        dataSource: "体育知识图谱",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "04:12",
        confidence: 85,
        input: "事件画像 + 体育内容策略",
        action: "SOP匹配：生成体育内容策略",
        output: "推荐精彩集锦+数据分析策略",
        dataSource: "SOP知识库",
      },
    ],
    similarCases: [
      {
        id: "CASE_008",
        title: "NBA总决赛关键战",
        similarity: 82,
        lifecycle: "爆发期",
        strategy: "精彩集锦 + 数据分析",
        effect: {
          playback: "+120%",
          engagement: "+18%",
        },
        date: "2025-06-10",
      },
    ],
    sopMatch: {
      id: "SOP-SPORT-001",
      name: "体育赛事-爆发期-低风险",
      confidence: 85,
      reason: "重大赛事，受众广泛",
      content: "采用精彩集锦+数据分析的策略，预期效果良好",
    },
    predictedEffect: {
      playback: { value: "+120%", baseline: "vs不运营" },
      engagement: { value: "+18%", baseline: "vs同类平均" },
      conversion: { value: "+2.8%", baseline: "粉丝转化率" },
    },
    riskWarnings: [],
    heatTrend: [
      { time: "04:00", value: 75 },
      { time: "06:00", value: 82 },
      { time: "08:00", value: 85 },
      { time: "10:00", value: 88, predicted: true },
      { time: "12:00", value: 82, predicted: true },
    ],
  },
  {
    id: "EVT_20260517_006",
    title: "暑期档电影票房破纪录，国产科幻片占比超40%",
    summary: "今年暑期档电影市场表现强劲，总票房创历史新高，国产科幻片表现亮眼",
    source: "微博热搜",
    heatScore: 78,
    heatLevel: "B" as const,
    lifecycle: "emerging" as const,
    lifecycleLabel: "萌芽期",
    riskLevel: "low" as const,
    eventType: "industry" as const,
    eventTypeLabel: "娱乐",
    publishedAt: "2026-05-17T07:00:00Z",
    ageHours: 3,
    scoreFactors: [
      { label: "时效信号", value: 26, max: 28, evidence: "3小时内发布" },
      { label: "传播速度", value: 15, max: 25, evidence: "传播速度中等" },
      { label: "作者密度", value: 10, max: 15, evidence: "部分娱乐博主关注" },
      { label: "情感倾向", value: 12, max: 15, evidence: "正向情感为主" },
      { label: "内容质量", value: 10, max: 15, evidence: "有票房数据" },
      { label: "平台适配度", value: 5, max: 17, evidence: "娱乐内容，受众广" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "07:05",
        confidence: 80,
        input: "微博热搜榜单",
        action: "发现线索：娱乐行业数据",
        output: "识别为B级娱乐事件",
        dataSource: "微博API",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "07:06",
        confidence: 78,
        input: "事件数据 + 行业分析",
        action: "事件聚类：评估行业影响",
        output: "热度78分(B级)，萌芽期，低风险",
        dataSource: "娱乐行业知识库",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "07:07",
        confidence: 75,
        input: "事件画像 + 娱乐内容策略",
        action: "SOP匹配：生成数据解读策略",
        output: "推荐数据可视化+趋势分析策略",
        dataSource: "SOP知识库",
      },
    ],
    similarCases: [
      {
        id: "CASE_009",
        title: "春节档票房创纪录",
        similarity: 75,
        lifecycle: "萌芽期 → 爆发期",
        strategy: "数据可视化 + 趋势分析",
        effect: {
          playback: "+65%",
          engagement: "+12%",
        },
        date: "2026-02-15",
      },
    ],
    sopMatch: {
      id: "SOP-ENT-003",
      name: "娱乐行业数据-萌芽期-低风险",
      confidence: 75,
      reason: "行业数据类内容，适合数据可视化",
      content: "采用数据可视化+趋势分析的策略",
    },
    predictedEffect: {
      playback: { value: "+65%", baseline: "vs不运营" },
      engagement: { value: "+12%", baseline: "vs同类平均" },
      conversion: { value: "+1.2%", baseline: "粉丝转化率" },
    },
    riskWarnings: [],
    heatTrend: [
      { time: "07:00", value: 72 },
      { time: "08:00", value: 76 },
      { time: "09:00", value: 78 },
      { time: "10:00", value: 82, predicted: true },
      { time: "11:00", value: 85, predicted: true },
    ],
  },
  {
    id: "EVT_20260517_007",
    title: "高校AI代写论文检测升级，多所院校发布禁令",
    summary: "多所高校升级AI代写检测系统，并发布明确禁令，引发学术界讨论",
    source: "Hacker News",
    heatScore: 68,
    heatLevel: "B" as const,
    lifecycle: "decline" as const,
    lifecycleLabel: "衰退期",
    riskLevel: "medium" as const,
    eventType: "industry" as const,
    eventTypeLabel: "教育",
    publishedAt: "2026-05-14T08:00:00Z",
    ageHours: 74,
    scoreFactors: [
      { label: "时效信号", value: 8, max: 28, evidence: "74小时前发布，进入衰退期" },
      { label: "传播速度", value: 12, max: 25, evidence: "传播速度较慢" },
      { label: "作者密度", value: 10, max: 15, evidence: "部分教育博主关注" },
      { label: "情感倾向", value: 10, max: 15, evidence: "情感中性" },
      { label: "内容质量", value: 18, max: 15, evidence: "有政策细节" },
      { label: "平台适配度", value: 10, max: 17, evidence: "教育类内容" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "08:05",
        confidence: 70,
        input: "Hacker News条目",
        action: "发现线索：教育政策类事件",
        output: "识别为B级教育事件，已进入衰退期",
        dataSource: "Hacker News API",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "08:06",
        confidence: 68,
        input: "事件数据 + 时效分析",
        action: "事件聚类：判定生命周期",
        output: "热度68分(B级)，衰退期，中等风险",
        dataSource: "教育知识库",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "08:07",
        confidence: 65,
        input: "事件画像 + 生命周期评估",
        action: "SOP匹配：建议观察为主",
        output: "建议只保留监控，除非出现二次传播信号",
        dataSource: "SOP知识库",
      },
    ],
    similarCases: [
      {
        id: "CASE_010",
        title: "AI学术诚信讨论",
        similarity: 68,
        lifecycle: "衰退期",
        strategy: "观察监控",
        effect: {
          playback: "+20%",
          engagement: "+5%",
        },
        date: "2025-09-10",
      },
    ],
    sopMatch: {
      id: "SOP-EDU-001",
      name: "教育政策类-衰退期-中风险",
      confidence: 65,
      reason: "已进入衰退期，建议观察",
      content: "建议只保留监控，除非出现二次传播信号",
    },
    predictedEffect: {
      playback: { value: "+20%", baseline: "vs不运营" },
      engagement: { value: "+5%", baseline: "vs同类平均" },
      conversion: { value: "+0.5%", baseline: "粉丝转化率" },
    },
    riskWarnings: [
      {
        level: "medium" as const,
        message: "教育政策类内容，需注意表述",
        detail: "避免引导学生规避检测，强调学术诚信",
      },
    ],
    heatTrend: [
      { time: "08:00", value: 75 },
      { time: "20:00", value: 70 },
      { time: "08:00", value: 68 },
      { time: "20:00", value: 65, predicted: true },
      { time: "08:00", value: 62, predicted: true },
    ],
  },
  {
    id: "EVT_20260517_008",
    title: "Apple Intelligence中文版本正式上线，Siri升级引发热议",
    summary: "苹果正式发布Apple Intelligence中文版本，Siri智能助手获得重大升级",
    source: "抖音站内",
    heatScore: 92,
    heatLevel: "S" as const,
    lifecycle: "burst" as const,
    lifecycleLabel: "爆发期",
    riskLevel: "low" as const,
    eventType: "ai-product" as const,
    eventTypeLabel: "产品更新",
    publishedAt: "2026-05-16T20:00:00Z",
    ageHours: 14,
    scoreFactors: [
      { label: "时效信号", value: 21, max: 28, evidence: "14小时内，仍在热度窗口" },
      { label: "传播速度", value: 23, max: 25, evidence: "苹果官方发布，传播迅速" },
      { label: "作者密度", value: 14, max: 15, evidence: "多个科技博主报道" },
      { label: "情感倾向", value: 15, max: 15, evidence: "高度正向，用户期待" },
      { label: "内容质量", value: 14, max: 15, evidence: "有产品演示" },
      { label: "平台适配度", value: 5, max: 17, evidence: "产品类内容，受众广" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "20:10",
        confidence: 93,
        input: "抖音科技热点",
        action: "发现线索：苹果重大产品更新",
        output: "识别为S级产品更新事件",
        dataSource: "抖音科技频道",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "20:11",
        confidence: 90,
        input: "事件数据 + 产品分析",
        action: "事件聚类：评估产品影响",
        output: "热度92分(S级)，爆发期，低风险",
        dataSource: "产品知识图谱",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "20:12",
        confidence: 88,
        input: "事件画像 + 产品内容策略",
        action: "SOP匹配：生成产品测评策略",
        output: "匹配SOP-TECH-002，推荐功能测评+使用教程",
        dataSource: "SOP知识库",
      },
    ],
    similarCases: [
      {
        id: "CASE_011",
        title: "iOS 18发布",
        similarity: 88,
        lifecycle: "爆发期 → 成熟期",
        strategy: "功能测评 + 使用教程",
        effect: {
          playback: "+180%",
          engagement: "+25%",
        },
        date: "2024-09-16",
      },
      {
        id: "CASE_012",
        title: "Apple Vision Pro上市",
        similarity: 75,
        lifecycle: "爆发期",
        strategy: "产品体验 + 场景应用",
        effect: {
          playback: "+150%",
          engagement: "+20%",
        },
        date: "2024-02-02",
      },
    ],
    sopMatch: {
      id: "SOP-TECH-002",
      name: "重大产品更新-爆发期-低风险",
      confidence: 88,
      reason: "苹果重大产品更新，用户关注度高",
      content: "采用功能测评+使用教程的策略，预期效果显著",
    },
    predictedEffect: {
      playback: { value: "+180%", baseline: "vs不运营" },
      engagement: { value: "+25%", baseline: "vs同类平均" },
      conversion: { value: "+4.5%", baseline: "粉丝转化率" },
    },
    riskWarnings: [],
    heatTrend: [
      { time: "20:00", value: 85 },
      { time: "22:00", value: 88 },
      { time: "00:00", value: 90 },
      { time: "02:00", value: 92 },
      { time: "04:00", value: 95, predicted: true },
      { time: "06:00", value: 98, predicted: true },
    ],
  },
  {
    id: "EVT_20260517_009",
    title: "某AI换脸诈骗案破获，涉案金额超千万，警方发布防范指南",
    summary: "警方破获一起利用AI换脸技术实施诈骗的案件，涉案金额超千万元，并发布防范指南",
    source: "新闻网站",
    heatScore: 80,
    heatLevel: "A" as const,
    lifecycle: "emerging" as const,
    lifecycleLabel: "萌芽期",
    riskLevel: "high" as const,
    eventType: "industry" as const,
    eventTypeLabel: "社会",
    publishedAt: "2026-05-17T05:00:00Z",
    ageHours: 5,
    scoreFactors: [
      { label: "时效信号", value: 26, max: 28, evidence: "5小时内发布" },
      { label: "传播速度", value: 18, max: 25, evidence: "传播速度较快" },
      { label: "作者密度", value: 11, max: 15, evidence: "多家媒体报道" },
      { label: "情感倾向", value: 8, max: 15, evidence: "情感负向，警示性强" },
      { label: "内容质量", value: 12, max: 15, evidence: "有案件细节和防范指南" },
      { label: "平台适配度", value: 5, max: 17, evidence: "社会安全类内容" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "05:10",
        confidence: 85,
        input: "新闻网站条目",
        action: "发现线索：AI安全事件",
        output: "识别为A级社会安全事件，极高风险",
        dataSource: "新闻聚合API",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "05:11",
        confidence: 82,
        input: "事件数据 + 安全分析",
        action: "事件聚类：评估社会影响",
        output: "热度80分(A级)，萌芽期，极高风险",
        dataSource: "安全知识库",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "05:12",
        confidence: 78,
        input: "事件画像 + 风险评估",
        action: "SOP匹配：生成安全科普策略",
        output: "匹配SOP-CRISIS-001，需严格审核",
        dataSource: "SOP知识库",
      },
    ],
    similarCases: [
      {
        id: "CASE_013",
        title: "AI诈骗案件警示",
        similarity: 80,
        lifecycle: "萌芽期 → 爆发期",
        strategy: "安全科普 + 防范指南",
        effect: {
          playback: "+95%",
          engagement: "+15%",
        },
        date: "2025-08-20",
      },
    ],
    sopMatch: {
      id: "SOP-CRISIS-001",
      name: "安全危机类-萌芽期-极高风险",
      confidence: 78,
      reason: "涉及社会安全，需严格审核",
      content: "采用安全科普+防范指南的策略，避免引发恐慌，需人工复核",
    },
    predictedEffect: {
      playback: { value: "+95%", baseline: "vs不运营" },
      engagement: { value: "+15%", baseline: "vs同类平均" },
      conversion: { value: "+2.5%", baseline: "粉丝转化率" },
    },
    riskWarnings: [
      {
        level: "high" as const,
        message: "涉及社会安全，需严格审核",
        detail: "避免引发恐慌，强调防范措施，需人工复核后发布",
      },
    ],
    heatTrend: [
      { time: "05:00", value: 72 },
      { time: "07:00", value: 78 },
      { time: "09:00", value: 80 },
      { time: "11:00", value: 85, predicted: true },
      { time: "13:00", value: 88, predicted: true },
    ],
  },
  {
    id: "EVT_20260517_010",
    title: "知名歌手新专辑上线，3小时播放量破亿",
    summary: "知名歌手发布新专辑，上线3小时播放量突破1亿次，创造新纪录",
    source: "微博热搜",
    heatScore: 88,
    heatLevel: "A" as const,
    lifecycle: "mature" as const,
    lifecycleLabel: "成熟期",
    riskLevel: "low" as const,
    eventType: "industry" as const,
    eventTypeLabel: "娱乐",
    publishedAt: "2026-05-16T12:00:00Z",
    ageHours: 22,
    scoreFactors: [
      { label: "时效信号", value: 21, max: 28, evidence: "22小时内，仍在热度窗口" },
      { label: "传播速度", value: 22, max: 25, evidence: "传播速度快" },
      { label: "作者密度", value: 13, max: 15, evidence: "多个娱乐博主报道" },
      { label: "情感倾向", value: 14, max: 15, evidence: "高度正向，粉丝热情" },
      { label: "内容质量", value: 13, max: 15, evidence: "有音乐片段和数据" },
      { label: "平台适配度", value: 5, max: 17, evidence: "娱乐内容，受众广" },
    ],
    agentChain: [
      {
        id: "perceive" as const,
        name: "感知Agent",
        timestamp: "12:10",
        confidence: 90,
        input: "微博热搜榜单",
        action: "发现线索：音乐发行重大事件",
        output: "识别为A级娱乐事件",
        dataSource: "微博API",
      },
      {
        id: "mine" as const,
        name: "挖掘Agent",
        timestamp: "12:11",
        confidence: 88,
        input: "事件数据 + 娱乐分析",
        action: "事件聚类：评估娱乐影响",
        output: "热度88分(A级)，成熟期，低风险",
        dataSource: "娱乐知识图谱",
      },
      {
        id: "strategy" as const,
        name: "运营Agent",
        timestamp: "12:12",
        confidence: 85,
        input: "事件画像 + 娱乐内容策略",
        action: "SOP匹配：生成音乐内容策略",
        output: "推荐音乐解读+粉丝互动策略",
        dataSource: "SOP知识库",
      },
    ],
    similarCases: [
      {
        id: "CASE_014",
        title: "热门歌手新歌发布",
        similarity: 85,
        lifecycle: "成熟期",
        strategy: "音乐解读 + 粉丝互动",
        effect: {
          playback: "+110%",
          engagement: "+20%",
        },
        date: "2026-03-20",
      },
    ],
    sopMatch: {
      id: "SOP-ENT-004",
      name: "音乐发行类-成熟期-低风险",
      confidence: 85,
      reason: "音乐发行事件，粉丝基础好",
      content: "采用音乐解读+粉丝互动的策略，预期效果良好",
    },
    predictedEffect: {
      playback: { value: "+110%", baseline: "vs不运营" },
      engagement: { value: "+20%", baseline: "vs同类平均" },
      conversion: { value: "+3.2%", baseline: "粉丝转化率" },
    },
    riskWarnings: [],
    heatTrend: [
      { time: "12:00", value: 82 },
      { time: "16:00", value: 86 },
      { time: "20:00", value: 88 },
      { time: "00:00", value: 90, predicted: true },
      { time: "04:00", value: 85, predicted: true },
    ],
  },
];

// 导出类型
export type MockEvent = typeof mockEvents[0];
